  common_steps: &microservice_build
    - label: "Build {{matrix}} - ${SERVICE_NAME}"
      key: "build-{{matrix}}-${SERVICE_NAME}"
      matrix: ["amd64", "arm64"]
      command: |
        echo "Building ${SERVICE_NAME} for {{matrix}}"

    - label: "Test - ${SERVICE_NAME}"
      key: "test-${SERVICE_NAME}"
      depends_on:
        - key: "build-amd64-${SERVICE_NAME}"
        - key: "build-arm64-${SERVICE_NAME}"
      command: "echo Testing ${SERVICE_NAME}"

  steps:
    - <<: *microservice_build
      if_changed: "services/auth/**"
      env:
        SERVICE_NAME: "auth-service"

    - <<: *microservice_build
      if_changed: "services/payment/**"
      env:
        SERVICE_NAME: "payment-service"

    - <<: *microservice_build
      if_changed: "services/notification/**"
      env:
        SERVICE_NAME: "notification-service"