  steps:
    - label: "Build and Test - {{matrix}}"
      key: "build"
      matrix:
        - "amd64"
        - "arm64"
      if_changed: "**/*"
      command: |
        echo "Building for architecture: {{matrix}}"
        echo "This would normally build your container for {{matrix}}"
        echo "Files that changed in this build:"
        git diff --name-only HEAD~1 || echo "No previous commit to diff against"
      agents:
        queue: ${AGENT_QUEUE:-"default"}

    - label: "Deploy Multi-arch"
      if_changed: "**/*"
      depends_on:
        - "build"
      command: |
        echo "Both architectures built successfully!"
        echo "Would deploy multi-arch manifest here"