configs:
  - &docker-with-buildkite-agent-cli
    docker#v5.12.0:
      propagate-environment: true
      mount-buildkite-agent: true
      mount-ssh-agent: true
      environment:
        - BUILDKITE_AGENT_AWS_KMS_KEY: hello-world

steps:
  - label: "Test docker"
    plugins:
      - *docker-with-buildkite-agent-cli
    command:
      - echo "--- Checking environment variables"
      - echo "BUILDKITE_AGENT_AWS_KMS_KEY = $BUILDKITE_AGENT_AWS_KMS_KEY"
      - echo "BUILDKITE_AGENT_CONFIG = $BUILDKITE_AGENT_CONFIG"
      - echo "--- Checking buildkite-agent config file"
      - cat /etc/buildkite-agent/buildkite-agent.cfg