
steps:
  - label: ":pipeline: Pipeline upload w/ success"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-success.yml"

  - label: ":pipeline: Pipeline upload w/ failure"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-fail.yml"

  - wait: ~
    continue_on_failure: true

  - group: ":buildkite: End Notification"
    steps:
      - label: ":buildkite: End Notification"
        command: "echo 'Build NOT failed!'"
        if : build.state == "passed"

      - label: ":buildkite: End Notification"
        command: "echo 'Build failed!'"
        if: build.state == "failing"