
steps:
  - label: ":buildkite: Start Notification"
    command: "echo 'hello world'"

  - label: ":pipeline: Pipeline upload w/ success"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-success.yml"

  - label: ":pipeline: Pipeline upload w/ failure"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-fail.yml"

  - wait: ~
    continue_on_failure: true

  - label: ":x: Build Failed Notification"
    command: "echo 'Build failed'"
    if: build.state == "failing" || build.state == "failed"

  - label: ":white_check_mark: Build Success Notification"
    command: "echo 'Build not failing!'"
    if: build.state != "failed"

