steps:
  - label: "Upload staging pipeline"
    command: |
      buildkite-agent pipeline upload <<YAML
        env:
          ENV_VAR: "staging"

        steps:
          - wait
          - command: echo \$\${ENV_VAR}
            env:
              ENV_VAR: "staging-2"
      YAML
  - label: "Upload prod pipeline"
    command: |
      buildkite-agent pipeline upload <<YAML
        env:
          ENV_VAR: "prod"

        steps:
          - wait
          - command: echo \$\${ENV_VAR}
            env:
              ENV_VAR: "prod-override"
      YAML