steps:
  - label: "Upload staging pipeline"
    command: |
      buildkite-agent pipeline upload ./buildkite/staging.yml

  - label: "Upload prod pipeline"
    command: buildkite-agent pipeline upload .buildkite/prod.yml