steps:
  - label: "Command"
    commands:
      - echo "Hello World"
    key: hello-world

  - block: "Release"
    prompt: "Fill out the details for release"
    fields:
      - text: "Release Name"
        key: "release-name"
    key: release-block
    depends_on: hello-world

  - label: "New Pipeline"
    commands:
      - sh ./.buildkite/scripts/new_build.sh
    depends_on: release-block