steps:
  - label: "Test docker"
    plugins:
      docker#v5.12.0:
        image: "buildkite/agent:latest"
        propagate-environment: true
        mount-ssh-agent: true
        environment:
          - BUILDKITE_AGENT_AWS_KMS_KEY
    command:
      - echo "BUILDKITE_AGENT_AWS_KMS_KEY = $BUILDKITE_AGENT_AWS_KMS_KEY"
      - buildkite-agent pipeline upload .buildkite/pipeline.yml