
steps:
  - label: ":buildkite: Start Notification"
    command: "exit 1'"

  - label: ":pipeline: Pipeline upload w/ success"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-success.yml"

  - label: ":pipeline: Pipeline upload w/ failure"
    command: "buildkite-agent pipeline upload .buildkite/pipeline-fail.yml"

  - wait: ~
    continue_on_failure: true

  - group: ":buildkite: End Notification"
    steps:
      - label: ":buildkite: End Notification"
        command: "echo 'Works as expected!'"
        if : build.state != "failing"
      - label: ":buildkite: End Notification"
        command: "echo 'Build failed!'"
        if: build.state == "failing"