steps:
  - label: "Test docker"
    plugins:
      docker#v5.12.0:
        image: "alpine:latest"
        propagate-environment: true
        mount-buildkite-agent: true
        mount-ssh-agent: true
        environment:
          - BUILDKITE_AGENT_AWS_KMS_KEY
    command:
      - echo "BUILDKITE_AGENT_AWS_KMS_KEY = $BUILDKITE_AGENT_AWS_KMS_KEY"
      - ls -la $BUILDKITE_AGENT_BINARY_PATH || echo "BUILDKITE_AGENT_BINARY_PATH not set"
      - chmod +x $BUILDKITE_AGENT_BINARY_PATH
      - buildkite-agent pipeline upload